# Data Generation

defaults:
  - config

hydra:
  run:
    dir: ${docker_volume_dir}

data_dir: ${shared_docker_volume_dir}/storage/data  # where to store dataset
assets_root: ${docker_volume_dir}/simulation/environments/assets/
disp: True  # visualize PyBullet
shared_memory: False
task: picking-seen-google-objects-seq
mode: test # 'train' or 'valid' or 'test'
n_perspectives: 50
n: 2504 # number of demos to generate
save_data: True  # write episodes to disk

dataset:
  type: 'single' # 'single' or 'multi'
  images: True
  cache: True # load episodes to memory instead of reading from disk
  batch_size: 3
  augment:
    theta_sigma: 60 # rotation sigma in degrees; N(mu = 0, sigma = theta_sigma).

# record videos (super slow)
record:
  save_video: False
  save_video_path: ${data_dir}/${task}-${mode}/videos/
  add_text: False
  fps: 20
  video_height: 640
  video_width: 720
